// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmldanbrxdeuhndoubqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbGRhbmJyeGRldWhuZG91YnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzM2MjAsImV4cCI6MjA2NTE0OTYyMH0.ZeBQoefQJ8J_d8oieGrwQJwBTPPL-arHYVMtnPqF6qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);